// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nas.Infrastructure.Persistence.Cluster;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Nas.Infrastructure.Persistence.Cluster.Migrations
{
    [DbContext(typeof(ClusterDbContext))]
    [Migration("20260718142143_AddBootstrapAdministratorAuthentication")]
    partial class AddBootstrapAdministratorAuthentication
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("9aeb2b37-3d2a-4f6f-9068-44ca9f20a301"),
                            RoleId = new Guid("3791e91b-bcd4-4f80-8f38-e9d7acb998c6")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Nas.Infrastructure.Persistence.Cluster.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClusterId")
                        .HasColumnType("uuid");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid?>("NodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClusterId", "CreatedAt");

                    b.ToTable("AuditEvents", (string)null);
                });

            modelBuilder.Entity("Nas.Infrastructure.Persistence.Cluster.ClusterRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Clusters", (string)null);
                });

            modelBuilder.Entity("Nas.Infrastructure.Persistence.Cluster.GlobalOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClusterId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("FencingToken")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ClusterId", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("NodeId", "Status", "CreatedAt");

                    b.ToTable("Operations", (string)null);
                });

            modelBuilder.Entity("Nas.Infrastructure.Persistence.Cluster.NasRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("3791e91b-bcd4-4f80-8f38-e9d7acb998c6"),
                            ConcurrencyStamp = "2c7339d4-7a32-4cf2-9884-7ac8440dfe74",
                            Name = "admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Nas.Infrastructure.Persistence.Cluster.NasUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<long>("SecurityVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("9aeb2b37-3d2a-4f6f-9068-44ca9f20a301"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3e898478-8913-4472-a9cf-5d5e5d8e15f6",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EmailConfirmed = false,
                            LockoutEnabled = true,
                            MustChangePassword = true,
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEHd07/lWDHilbuTDL9jBep584Mmn77geD/ljDTSGiuqv2WR1QYUhMAMSx3P9qas4Kg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0bb934c2-07fa-451d-923f-31b113e8fb6a",
                            SecurityVersion = 0L,
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("Nas.Infrastructure.Persistence.Cluster.NodeRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClusterId")
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("IsControlEligible")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ClusterId", "DisplayName")
                        .IsUnique();

                    b.ToTable("Nodes", (string)null);
                });

            modelBuilder.Entity("Nas.Infrastructure.Persistence.Cluster.PermissionRecord", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Code");

                    b.ToTable("Permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "storage.read",
                            Description = "storage.read"
                        },
                        new
                        {
                            Code = "storage.write",
                            Description = "storage.write"
                        },
                        new
                        {
                            Code = "storage.format",
                            Description = "storage.format"
                        },
                        new
                        {
                            Code = "raid.manage",
                            Description = "raid.manage"
                        },
                        new
                        {
                            Code = "share.read",
                            Description = "share.read"
                        },
                        new
                        {
                            Code = "share.manage",
                            Description = "share.manage"
                        },
                        new
                        {
                            Code = "user.read",
                            Description = "user.read"
                        },
                        new
                        {
                            Code = "user.manage",
                            Description = "user.manage"
                        },
                        new
                        {
                            Code = "network.read",
                            Description = "network.read"
                        },
                        new
                        {
                            Code = "network.manage",
                            Description = "network.manage"
                        },
                        new
                        {
                            Code = "service.read",
                            Description = "service.read"
                        },
                        new
                        {
                            Code = "service.manage",
                            Description = "service.manage"
                        },
                        new
                        {
                            Code = "docker.read",
                            Description = "docker.read"
                        },
                        new
                        {
                            Code = "docker.manage",
                            Description = "docker.manage"
                        },
                        new
                        {
                            Code = "backup.read",
                            Description = "backup.read"
                        },
                        new
                        {
                            Code = "backup.manage",
                            Description = "backup.manage"
                        },
                        new
                        {
                            Code = "system.reboot",
                            Description = "system.reboot"
                        },
                        new
                        {
                            Code = "system.shutdown",
                            Description = "system.shutdown"
                        },
                        new
                        {
                            Code = "logs.read",
                            Description = "logs.read"
                        });
                });

            modelBuilder.Entity("Nas.Infrastructure.Persistence.Cluster.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<string>("PermissionCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("RoleId", "PermissionCode");

                    b.HasIndex("PermissionCode");

                    b.ToTable("RolePermissions", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("3791e91b-bcd4-4f80-8f38-e9d7acb998c6"),
                            PermissionCode = "storage.read"
                        },
                        new
                        {
                            RoleId = new Guid("3791e91b-bcd4-4f80-8f38-e9d7acb998c6"),
                            PermissionCode = "storage.write"
                        },
                        new
                        {
                            RoleId = new Guid("3791e91b-bcd4-4f80-8f38-e9d7acb998c6"),
                            PermissionCode = "storage.format"
                        },
                        new
                        {
                            RoleId = new Guid("3791e91b-bcd4-4f80-8f38-e9d7acb998c6"),
                            PermissionCode = "raid.manage"
                        },
                        new
                        {
                            RoleId = new Guid("3791e91b-bcd4-4f80-8f38-e9d7acb998c6"),
                            PermissionCode = "share.read"
                        },
                        new
                        {
                            RoleId = new Guid("3791e91b-bcd4-4f80-8f38-e9d7acb998c6"),
                            PermissionCode = "share.manage"
                        },
                        new
                        {
                            RoleId = new Guid("3791e91b-bcd4-4f80-8f38-e9d7acb998c6"),
                            PermissionCode = "user.read"
                        },
                        new
                        {
                            RoleId = new Guid("3791e91b-bcd4-4f80-8f38-e9d7acb998c6"),
                            PermissionCode = "user.manage"
                        },
                        new
                        {
                            RoleId = new Guid("3791e91b-bcd4-4f80-8f38-e9d7acb998c6"),
                            PermissionCode = "network.read"
                        },
                        new
                        {
                            RoleId = new Guid("3791e91b-bcd4-4f80-8f38-e9d7acb998c6"),
                            PermissionCode = "network.manage"
                        },
                        new
                        {
                            RoleId = new Guid("3791e91b-bcd4-4f80-8f38-e9d7acb998c6"),
                            PermissionCode = "service.read"
                        },
                        new
                        {
                            RoleId = new Guid("3791e91b-bcd4-4f80-8f38-e9d7acb998c6"),
                            PermissionCode = "service.manage"
                        },
                        new
                        {
                            RoleId = new Guid("3791e91b-bcd4-4f80-8f38-e9d7acb998c6"),
                            PermissionCode = "docker.read"
                        },
                        new
                        {
                            RoleId = new Guid("3791e91b-bcd4-4f80-8f38-e9d7acb998c6"),
                            PermissionCode = "docker.manage"
                        },
                        new
                        {
                            RoleId = new Guid("3791e91b-bcd4-4f80-8f38-e9d7acb998c6"),
                            PermissionCode = "backup.read"
                        },
                        new
                        {
                            RoleId = new Guid("3791e91b-bcd4-4f80-8f38-e9d7acb998c6"),
                            PermissionCode = "backup.manage"
                        },
                        new
                        {
                            RoleId = new Guid("3791e91b-bcd4-4f80-8f38-e9d7acb998c6"),
                            PermissionCode = "system.reboot"
                        },
                        new
                        {
                            RoleId = new Guid("3791e91b-bcd4-4f80-8f38-e9d7acb998c6"),
                            PermissionCode = "system.shutdown"
                        },
                        new
                        {
                            RoleId = new Guid("3791e91b-bcd4-4f80-8f38-e9d7acb998c6"),
                            PermissionCode = "logs.read"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Nas.Infrastructure.Persistence.Cluster.NasRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Nas.Infrastructure.Persistence.Cluster.NasUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Nas.Infrastructure.Persistence.Cluster.NasUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Nas.Infrastructure.Persistence.Cluster.NasRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nas.Infrastructure.Persistence.Cluster.NasUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Nas.Infrastructure.Persistence.Cluster.NasUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nas.Infrastructure.Persistence.Cluster.GlobalOperation", b =>
                {
                    b.HasOne("Nas.Infrastructure.Persistence.Cluster.ClusterRecord", null)
                        .WithMany()
                        .HasForeignKey("ClusterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nas.Infrastructure.Persistence.Cluster.NodeRegistration", null)
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nas.Infrastructure.Persistence.Cluster.NasUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Nas.Infrastructure.Persistence.Cluster.NodeRegistration", b =>
                {
                    b.HasOne("Nas.Infrastructure.Persistence.Cluster.ClusterRecord", null)
                        .WithMany()
                        .HasForeignKey("ClusterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Nas.Infrastructure.Persistence.Cluster.RolePermission", b =>
                {
                    b.HasOne("Nas.Infrastructure.Persistence.Cluster.PermissionRecord", null)
                        .WithMany()
                        .HasForeignKey("PermissionCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nas.Infrastructure.Persistence.Cluster.NasRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
